AWSTemplateFormatVersion: 2010-09-09

Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true
      InstanceTenancy: default
      Tags: 
        - Key: "Name"
          Value: "VPC"
  PublicSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: 10.0.1.0/24
      AvailabilityZone: "ap-northeast-1c"
      Tags:
        - Key: "Name"
          Value: "publicSubnet"
  MyIGW:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: "Name"
          Value: "igw-vcp"
  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref VPC
      InternetGatway: !Ref MyIGW
  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    DependsOn: AttachGateway
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: "rtb-vpc"
  AttachPublicRouteTableToPublicSubnet:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref PublicRouteTable
      SubnetId: !Ref PublicSubnet
  MyRoute:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref PublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: MyIGW

  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: aws-network-basis
      GroupDescription: "Security group for web server instance"
      SecurityGroupIngress:
        - CidrIp: 0.0.0.0/0
          Description: "SSH"
          FromProt: 22
          IpProtocol: "tcp"
          ToPort: 22
      VpcId: !Ref VPC

  # EC2: Webserver
  EC2:
    Type: AWS::EC2::Instance
    Properties:
      imageId: "ami-a77c30c1"
      KeyName: "aws-network-basis"
      InstanceType: "t2.micro"
      NetworkInterfaces:
        - AssociatePublicIpAddress: true
          DeviceIndex: 0
          DeleteOnTermination: true
          PrivateIpAddress: 10.0.1.10
          SubnetId: !Ref PublicSubnet
          GroupSet: !Ref SecurityGroup
      # strage
      BlockDevicemappings:
        - Devicename: /dev/xvda
          Ebs:
            VolumeType: standard
            VolumeSize: 8
            DeleteOnTermination: true
      Tags:
        - Key: Name
          Value: "aws-network-basis-instance"

